/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class ExemploInterface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExemploInterface.class.getName());

    /**
     * Creates new form ExemploInterface
     */
    
    double n1, n2;
    String operacao;
    
    public ExemploInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btn7 = new javax.swing.JButton();
        btnDivisao = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnSoma = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnSubtracao = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnPercent = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        btnMultiplicacao = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnVirgula = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        btnBackspace = new javax.swing.JButton();
        btnExpoente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btnDivisao.setText("÷");
        btnDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisaoActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnSoma.setText("+");
        btnSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomaActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btnSubtracao.setText("-");
        btnSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtracaoActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnPercent.setText("%");
        btnPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnResultado.setText("=");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });

        btnMultiplicacao.setText("*");
        btnMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacaoActionPerformed(evt);
            }
        });

        btnRaiz.setText("√");
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnVirgula.setText(",");
        btnVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVirgulaActionPerformed(evt);
            }
        });

        txtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnBackspace.setText("⌫");
        btnBackspace.setToolTipText("");
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackspaceActionPerformed(evt);
            }
        });

        btnExpoente.setText("x²");
        btnExpoente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpoenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBackspace)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnVirgula)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn6)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSubtracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDivisao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPercent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnC)
                                .addComponent(btnExpoente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRaiz)
                    .addComponent(btnPercent)
                    .addComponent(btnExpoente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDivisao)
                    .addComponent(btnCE)
                    .addComponent(btnC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7)
                    .addComponent(btn8)
                    .addComponent(btn9)
                    .addComponent(btnMultiplicacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4)
                    .addComponent(btnSoma)
                    .addComponent(btn5)
                    .addComponent(btn6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btnSubtracao)
                    .addComponent(btn2)
                    .addComponent(btn3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0)
                    .addComponent(btnResultado)
                    .addComponent(btnVirgula)
                    .addComponent(btnBackspace))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        txtResultado.setText(txtResultado.getText() + "4");
    }                                    

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        txtResultado.setText(txtResultado.getText() + "5");
    }                                    

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {                                        
        lblValor.setText("√" + txtResultado.getText());
        n1 = Double.parseDouble(txtResultado.getText());
        operacao = "raiz";
        txtResultado.setText("");
    }                                       

    private void btnMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        lblValor.setText(txtResultado.getText()+"*");
        n1 = Double.parseDouble(txtResultado.getText());
        operacao = "multiplicacao";
        txtResultado.setText("");
    }                                                

    private void btnVirgulaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        txtResultado.setText(txtResultado.getText() + "1");
    }                                    

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        double resultado;

    if (operacao.equals("soma")) {
        n2 = Double.parseDouble(txtResultado.getText());
        resultado = n1 + n2;
        lblValor.setText(n1 + " + " + n2 + " =");
        txtResultado.setText(String.valueOf(resultado));

    } else if (operacao.equals("subtracao")) {
        n2 = Double.parseDouble(txtResultado.getText());
        resultado = n1 - n2;
        lblValor.setText(n1 + " - " + n2 + " =");
        txtResultado.setText(String.valueOf(resultado));

    } else if (operacao.equals("multiplicacao")) {
        n2 = Double.parseDouble(txtResultado.getText());
        resultado = n1 * n2;
        lblValor.setText(n1 + " * " + n2 + " =");
        txtResultado.setText(String.valueOf(resultado));

    } else if (operacao.equals("divisao")) {
        n2 = Double.parseDouble(txtResultado.getText());

        if (n2 == 0) {
            txtResultado.setText("Erro");
            lblValor.setText("Não pode dividir por zero");
        } else {
            resultado = n1 / n2;
            lblValor.setText(n1 + " / " + n2 + " =");
            txtResultado.setText(String.valueOf(resultado));
        }

    } else if (operacao.equals("porcentagem")) {
        n2 = Double.parseDouble(txtResultado.getText());
        resultado = (n1 / 100) * n2;
        lblValor.setText(n1 + "% de " + n2 + " =");
        txtResultado.setText(String.valueOf(resultado));

    } else if (operacao.equals("raiz")) {
        resultado = Math.sqrt(n1);
        lblValor.setText("√" + n1 + " =");
        txtResultado.setText(String.valueOf(resultado));
    } else if (operacao.equals("expoente")) {
        resultado = n1 * n1;
        lblValor.setText(n1 + "² =");
        txtResultado.setText(String.valueOf(resultado));
    }
    }                                            

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        txtResultado.setText(txtResultado.getText() + "8");
    }                                    

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        txtResultado.setText(txtResultado.getText() + "7");
    }                                    

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        txtResultado.setText(txtResultado.getText() + "9");
    }                                    

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        txtResultado.setText(txtResultado.getText() + "6");
    }                                    

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        txtResultado.setText(txtResultado.getText() + "2");
    }                                    

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        txtResultado.setText(txtResultado.getText() + "3");
    }                                    

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        txtResultado.setText(txtResultado.getText() + "0");
    }                                    

    private void btnSomaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        lblValor.setText(txtResultado.getText()+"+");
        n1 = Double.parseDouble(txtResultado.getText());
        operacao = "soma";
        txtResultado.setText("");
    }                                       

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {                                             
       double resultado;
       n2 = Double.parseDouble(txtResultado.getText());
       if (operacao.equals("soma")){
           resultado = n1 + n2;
           lblValor.setText(n1 + "+" + n2 + "=");
           txtResultado.setText(String.valueOf(resultado));
       }
       if (operacao.equals("subtracao")){
           resultado = n1 + n2;
           lblValor.setText(n1 + "-" + n2 + "=");
           txtResultado.setText(String.valueOf(resultado));
       }
       if (operacao.equals("multiplicacao")){
           resultado = n1 + n2;
           lblValor.setText(n1 + "*" + n2 + "=");
           txtResultado.setText(String.valueOf(resultado));
       }
       if (operacao.equals("porcentagem")){
           resultado = n1 + n2;
           lblValor.setText(n1 + "%" + n2 + "=");
           txtResultado.setText(String.valueOf(resultado));
       }
       if (operacao.equals("porcentagem")) {
        resultado = (n1 / 100) * n2;
        lblValor.setText(n1 + "% =");
        txtResultado.setText(String.valueOf(resultado));
       }
       if (operacao.equals("raiz")) {
            resultado = Math.sqrt(n1);
            lblValor.setText(n1 + "√ =");
            txtResultado.setText(String.valueOf(resultado));
       }
       if (operacao.equals("expoente")) {
            resultado = Math.pow(n1, n2);
            lblValor.setText(n1 +"^"+n2+"=");
            txtResultado.setText(String.valueOf(resultado));
       }
       
    }                                            

    private void btnSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {                                             
       lblValor.setText(txtResultado.getText()+"-");
        n1 = Double.parseDouble(txtResultado.getText());
        operacao = "subtracao";
        txtResultado.setText("");
    }                                            

    private void btnDivisaoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        lblValor.setText(txtResultado.getText()+"/");
        n1 = Double.parseDouble(txtResultado.getText());
        operacao = "divisao";
        txtResultado.setText("");
    }                                          

    private void btnPercentActionPerformed(java.awt.event.ActionEvent evt) {                                           
        lblValor.setText(txtResultado.getText() + "%");
        n1 = Double.parseDouble(txtResultado.getText());
        operacao = "porcentagem";
        txtResultado.setText("");
    }                                          

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {                                     
        txtResultado.setText("");
        lblValor.setText("");
        
        n1 = 0;
        n2 = 0;
        operacao = ""; 
    }                                    

    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String textoAtual = txtResultado.getText();
        
        if (textoAtual.length() > 0) {
            textoAtual = textoAtual.substring(0, textoAtual.length() - 1);
            
            txtResultado.setText(textoAtual);
        }
    }                                            

    private void btnExpoenteActionPerformed(java.awt.event.ActionEvent evt) {                                            
        lblValor.setText(txtResultado.getText() + "²");
    n1 = Double.parseDouble(txtResultado.getText());
    operacao = "expoente";
    txtResultado.setText("");
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ExemploInterface().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnDivisao;
    private javax.swing.JButton btnExpoente;
    private javax.swing.JButton btnMultiplicacao;
    private javax.swing.JButton btnPercent;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnSoma;
    private javax.swing.JButton btnSubtracao;
    private javax.swing.JButton btnVirgula;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration                   
}
