/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastroespecies;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.io.FileReader;
import java.io.BufferedReader;

/**
 *
 * @author bruno
 */
public class Cadastro extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadastro.class.getName());

    private ArrayList<CadastroEspecies> especies = new ArrayList<>();

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        carregarArquivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpSexo = new javax.swing.ButtonGroup();
        txtCientifico = new javax.swing.JTextField();
        lblNomeCientifico = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtApelido = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lblAltura = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        cmbGrupo = new javax.swing.JComboBox<>();
        lblGrupo = new javax.swing.JLabel();
        lblNomeCientifico2 = new javax.swing.JLabel();
        rdoMasculino = new javax.swing.JRadioButton();
        rdoFeminino = new javax.swing.JRadioButton();
        rdoHermafrodita = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEspecies = new javax.swing.JTable();
        btnExcluirEspecies = new javax.swing.JButton();
        btnCadastrar1 = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvarAlteracoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCientifico.addActionListener(this::txtCientificoActionPerformed);

        lblNomeCientifico.setText("Nome científico");

        jLabel2.setText("Apelido");

        txtApelido.addActionListener(this::txtApelidoActionPerformed);

        lblPeso.setText("Peso");

        txtPeso.addActionListener(this::txtPesoActionPerformed);

        lblAltura.setText("Altura");

        txtAltura.addActionListener(this::txtAlturaActionPerformed);

        cmbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mamíferos", "Aves", "Répteis", "Anfíbios", "Peixes", "Insetos", "Aracnídeos", "Crustáceos", "Moluscos", "Anelídeos", "Cnidários", "Equinodermos", "Poríferos", "Nematódeos" }));
        cmbGrupo.addActionListener(this::cmbGrupoActionPerformed);

        lblGrupo.setText("Grupo");

        lblNomeCientifico2.setText("Sexo");

        btnGrpSexo.add(rdoMasculino);
        rdoMasculino.setText("Masculino");
        rdoMasculino.addActionListener(this::rdoMasculinoActionPerformed);

        btnGrpSexo.add(rdoFeminino);
        rdoFeminino.setText("Feminino");

        btnGrpSexo.add(rdoHermafrodita);
        rdoHermafrodita.setText("Hermafrodita");

        tblEspecies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome científico", "Apelido", "Peso", "Altura", "Grupo", "Sexo"
            }
        ));
        jScrollPane1.setViewportView(tblEspecies);

        btnExcluirEspecies.setText("Excluir");
        btnExcluirEspecies.addActionListener(this::btnExcluirEspeciesActionPerformed);

        btnCadastrar1.setText("Cadastrar");
        btnCadastrar1.addActionListener(this::btnCadastrar1ActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnSalvarAlteracoes.setText("Salvar alterações");
        btnSalvarAlteracoes.addActionListener(this::btnSalvarAlteracoesActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeCientifico)
                                    .addComponent(txtCientifico, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGrupo)
                                    .addComponent(cmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeCientifico2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPeso)
                                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAltura)
                                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoMasculino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoFeminino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoHermafrodita))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnSalvarAlteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnExcluirEspecies, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAltura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeCientifico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCientifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrupo)
                    .addComponent(lblNomeCientifico2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoFeminino)
                    .addComponent(rdoHermafrodita)
                    .addComponent(rdoMasculino))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluirEspecies, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarAlteracoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCientificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCientificoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCientificoActionPerformed

    private void txtApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApelidoActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaActionPerformed

    private void rdoMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMasculinoActionPerformed

    private void cmbGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGrupoActionPerformed

    private void atualizarTabela() {
        // pegar o modelo da tabela
        // limpar as linhas
        // percorrer os alunos
        // adicionar cada aluno na tabela

        // pegar o modelo da tabela
        DefaultTableModel modelo
                = (DefaultTableModel) tblEspecies.getModel();

        // limpar as linhas
        modelo.setRowCount(0);

        for (CadastroEspecies especie : especies) {
            modelo.addRow(new Object[]{
                especie.getNomeCientifico(),
                especie.getApelido(),
                especie.getPeso(),
                especie.getAltura(),
                especie.getGrupo(),
                especie.getSexo()
            });
        }
    }

    private void salvarArquivo() {
        try {
            //Abre/cria o alunos.txt
            FileWriter arquivo = new FileWriter("especies.txt");

            //Escreve no alunos.txt
            for (CadastroEspecies especie : especies) {
                arquivo.write(especie.toString() + "\n");
            }

            // Fecha o arquivo
            arquivo.close();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar o arquivo!");
        }
    }

    private void carregarArquivo() {
        try {
            //Abre o arquivo para leitura
            FileReader arquivo = new FileReader("especies.txt");
            //Lê o arquivo
            BufferedReader leitor = new BufferedReader(arquivo);

            String linha;

            // Enquanto houver uma linha para ler, continue repetindo.
            while ((linha = leitor.readLine()) != null) {

                String[] dados = linha.split(";");

                CadastroEspecies especie = new CadastroEspecies(
                        dados[0],
                        dados[1],
                        Float.parseFloat(dados[2]),
                        Float.parseFloat(dados[3]),
                        dados[4],
                        dados[5]
                );

                especies.add(especie);

            }

            atualizarTabela();

        } catch (IOException e) {

        }
    }


    private void btnCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar1ActionPerformed
        try {

            // Pegando os dados dos campos
            // Radio
            String sexo = "";

            if (rdoMasculino.isSelected()) {
                sexo = "Masculino";
            } else if (rdoFeminino.isSelected()) {
                sexo = "Feminino";
            } else if (rdoHermafrodita.isSelected()) {
                sexo = "Hermafrodita";
            }

            // String 
            String nomeCientifico = txtCientifico.getText().trim();
            String apelido = txtApelido.getText().trim();

            // Combo 
            String grupo = cmbGrupo.getSelectedItem().toString();

            // Nome científico
            if (txtCientifico.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Digite o nome científico!"
                );
                return;
            }

            // Verifica campos obrigatórios
            if (nomeCientifico.isEmpty()
                    || apelido.isEmpty()
                    || txtPeso.getText().trim().isEmpty()
                    || txtAltura.getText().trim().isEmpty()
                    || grupo.isEmpty()
                    || sexo.isEmpty()) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Preencha todos os campos!"
                );
                return;
            }

            float peso = Float.parseFloat(
                    txtPeso.getText().trim().replace(",", ".")
            );

            float altura = Float.parseFloat(
                    txtAltura.getText().trim().replace(",", ".")
            );

            // Verifica se a matrícula já existe
            // private ArrayList<CadastroEspecies> especies = new ArrayList<>();
            // private ArrayList<Aluno> alunos = new ArrayList<>();
            // for (Aluno aluno : alunos) {
            for (CadastroEspecies especie : especies) {

                if (especie.getNomeCientifico().equals(nomeCientifico)) {

                    javax.swing.JOptionPane.showMessageDialog(
                            this,
                            "Esse nome científico já está cadastrado!"
                    );

                    return;
                }
            }

            // Cria o objeto Aluno
            CadastroEspecies especie = new CadastroEspecies(
                    nomeCientifico,
                    apelido,
                    peso,
                    altura,
                    grupo,
                    sexo
            );

            // Adiciona na lista
            especies.add(especie);

            // Adiciona na JTable, atualizando
            atualizarTabela();

            salvarArquivo();

            // Limpa os campos
            txtCientifico.setText("");
            txtApelido.setText("");
            txtPeso.setText("");
            txtAltura.setText("");
            cmbGrupo.setSelectedIndex(0);

            // Limpa os Radio Buttons
            rdoMasculino.setSelected(false);
            rdoFeminino.setSelected(false);
            rdoHermafrodita.setSelected(false);

        } catch (NumberFormatException e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    ""
            );
        }
    }

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {
        // Cria uma variável que guarda a linha selecionada
        int linha = tblEspecies.getSelectedRow();

        // Só remove se uma linha tiver selecionada. Se for diferente de -1 (indica que nenhuma linha foi selecionada) vai remover
        if (linha != -1) {
            especies.remove(linha);
            atualizarTabela();
            salvarArquivo();

        } else {
            JOptionPane.showMessageDialog(this, "Selecione um aluno para excluir!");
        }

        atualizarTabela();
    }//GEN-LAST:event_btnCadastrar1ActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Cria uma variável que guarda a linha selecionada
        int linha = tblEspecies.getSelectedRow();

        // Só edita se uma linha tiver selecionada. Se for diferente de -1 (indica que nenhuma linha foi selecionada) edita
        if (linha != -1) {

            CadastroEspecies especie = especies.get(linha);

            // Coloca os dados nos campos
            txtCientifico.setText(especie.getNomeCientifico());
            txtApelido.setText(especie.getApelido());

            // Se tiver peso e altura na tabela/classe
            txtPeso.setText(String.valueOf(especie.getPeso()));
            txtAltura.setText(String.valueOf(especie.getAltura()));

            // ComboBox
            cmbGrupo.setSelectedItem(especie.getGrupo());

            // Radio Buttons
            if (especie.getSexo().equals("Masculino")) {
                rdoMasculino.setSelected(true);
            } else if (especie.getSexo().equals("Feminino")) {
                rdoFeminino.setSelected(true);
            } else if (especie.getSexo().equals("Hermafrodita")) {
                rdoHermafrodita.setSelected(true);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma espécie para editar!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        int linha = tblEspecies.getSelectedRow();

        if (linha != -1) {

            CadastroEspecies especie = especies.get(linha);

            // String
            especie.setNomeCientifico(txtCientifico.getText().trim());
            especie.setApelido(txtApelido.getText().trim());

            // Float
            especie.setPeso(Float.parseFloat(txtPeso.getText().trim().replace(",", ".")));
            especie.setAltura(Float.parseFloat(txtAltura.getText().trim().replace(",", ".")));

            // ComboBox
            especie.setGrupo(cmbGrupo.getSelectedItem().toString());

            // RadioButton
            String sexo = "";

            if (rdoMasculino.isSelected()) {
                sexo = "Masculino";
            } else if (rdoFeminino.isSelected()) {
                sexo = "Feminino";
            } else if (rdoHermafrodita.isSelected()) {
                sexo = "Hermafrodita";
            }

            especie.setSexo(sexo);

            // Atualiza tabela e arquivo
            atualizarTabela();
            salvarArquivo();

            JOptionPane.showMessageDialog(this, "Alterações salvas!");

        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma espécie para editar!"
            );
        }
    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

    private void btnExcluirEspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEspeciesActionPerformed
        // Cria uma variável que guarda a linha selecionada
        int linha = tblEspecies.getSelectedRow();

        // Só remove se uma linha tiver selecionada. Se for diferente de -1 (indica que nenhuma linha foi selecionada) vai remover
        if (linha != -1) {
            especies.remove(linha);
            atualizarTabela();
            salvarArquivo();

        } else {
            JOptionPane.showMessageDialog(this, "Selecione um aluno para excluir!");
        }

        atualizarTabela();
    }//GEN-LAST:event_btnExcluirEspeciesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar1;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluirEspecies;
    private javax.swing.ButtonGroup btnGrpSexo;
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JComboBox<String> cmbGrupo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblNomeCientifico;
    private javax.swing.JLabel lblNomeCientifico2;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JRadioButton rdoFeminino;
    private javax.swing.JRadioButton rdoHermafrodita;
    private javax.swing.JRadioButton rdoMasculino;
    private javax.swing.JTable tblEspecies;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtCientifico;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
